
exports.seed = function(knex) {
  return knex('Activity_Type').insert([
    {
      Activity_Type_ID: 1, 
      Activity_Type_Name: 'RUNNING',
      Strava_Activity_Type_Name: 'Run',
      AppleHealth_Activity_Type_Name: 'Running',
    },
    {
      Activity_Type_ID: 2, 
      Activity_Type_Name: 'INDOOR RUNNING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 3, 
      Activity_Type_Name: 'OBSTACLE RUNNING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 4, 
      Activity_Type_Name: 'STREET RUNNING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 5, 
      Activity_Type_Name: 'TRACK RUNNING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 6, 
      Activity_Type_Name: 'TRAIL RUNNING',
      Strava_Activity_Type_Name: 'TrailRun',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 7, 
      Activity_Type_Name: 'TREADMILL RUNNING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 8, 
      Activity_Type_Name: 'ULTRA RUNNING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 9, 
      Activity_Type_Name: 'VIRTUAL RUNNING',
      Strava_Activity_Type_Name: 'VirtualRun',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 10, 
      Activity_Type_Name: 'CYCLING',
      Strava_Activity_Type_Name: 'Ride',
      AppleHealth_Activity_Type_Name: 'Cycling',
    },
    {
      Activity_Type_ID: 11, 
      Activity_Type_Name: 'BMX',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 12, 
      Activity_Type_Name: 'CYCLOCROSS',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 13, 
      Activity_Type_Name: 'DOWNHILL BIKING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 14, 
      Activity_Type_Name: 'GRAVEL',
      Strava_Activity_Type_Name: 'GravelRide',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 15, 
      Activity_Type_Name: 'INDOOR CYCLING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 16, 
      Activity_Type_Name: 'MOUNTAIN BIKING',
      Strava_Activity_Type_Name: 'MountainBikeRide/EMountainBikeRide',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 17, 
      Activity_Type_Name: 'RECUMBENT CYCLING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 18, 
      Activity_Type_Name: 'ROAD CYCLING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 19, 
      Activity_Type_Name: 'TRACK CYCLING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 20, 
      Activity_Type_Name: 'VIRTUAL CYCLING',
      Strava_Activity_Type_Name: 'VirtualRide',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 21, 
      Activity_Type_Name: 'GYM & FITNESS EQUIPMENT',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 22, 
      Activity_Type_Name: 'BOULDERING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 23, 
      Activity_Type_Name: 'ELLIPTICAL',
      Strava_Activity_Type_Name: 'Elliptical',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 24, 
      Activity_Type_Name: 'CARDIO',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 25, 
      Activity_Type_Name: 'INDOOR CLIMBING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 26, 
      Activity_Type_Name: 'INDOOR ROWING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 27, 
      Activity_Type_Name: 'PILATES',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 28, 
      Activity_Type_Name: 'STAIR STEPPER',
      Strava_Activity_Type_Name: 'StairStepper',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 29, 
      Activity_Type_Name: 'STRENGTH TRAINING',
      Strava_Activity_Type_Name: 'WeightTraining',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 30, 
      Activity_Type_Name: 'YOGA',
      Strava_Activity_Type_Name: 'Yoga',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 31, 
      Activity_Type_Name: 'HIKING',
      Strava_Activity_Type_Name: 'Hike',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 32, 
      Activity_Type_Name: 'SWIMMING',
      Strava_Activity_Type_Name: 'Swim',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 33, 
      Activity_Type_Name: 'POOL SWIMMING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 34, 
      Activity_Type_Name: 'OPEN WATER SWIMMING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 35, 
      Activity_Type_Name: 'WALKING',
      Strava_Activity_Type_Name: 'Walk',
      AppleHealth_Activity_Type_Name: 'Walking',
    },
    {
      Activity_Type_ID: 36, 
      Activity_Type_Name: 'CASUAL WALKING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 37, 
      Activity_Type_Name: 'SPEED WALKING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 38, 
      Activity_Type_Name: 'TRANSITION',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 39, 
      Activity_Type_Name: 'BIKE TO RUN TRANSITION',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 40, 
      Activity_Type_Name: 'RUN TO BIKE TRANSITION',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 41, 
      Activity_Type_Name: 'SWIM TO BIKE TRANSITION',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 42, 
      Activity_Type_Name: 'MOTORCYCLING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 43, 
      Activity_Type_Name: 'ATV',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 44, 
      Activity_Type_Name: 'MOTOCROSS',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 45, 
      Activity_Type_Name: 'OTHER',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 46, 
      Activity_Type_Name: 'ASSISTANCE',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 47, 
      Activity_Type_Name: 'AUTO RACING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 48, 
      Activity_Type_Name: 'BOATING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 49, 
      Activity_Type_Name: 'BREATHWORK',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 50, 
      Activity_Type_Name: 'DRIVING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 51, 
      Activity_Type_Name: 'FLOOR CLIMBING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: 'StairClimbing',
    },
    {
      Activity_Type_ID: 52, 
      Activity_Type_Name: 'FLYING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 53, 
      Activity_Type_Name: 'GOLF',
      Strava_Activity_Type_Name: 'Golf',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 54, 
      Activity_Type_Name: 'HANG GLIDING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 55, 
      Activity_Type_Name: 'HORSEBACK RIDING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 56, 
      Activity_Type_Name: 'FISHING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 57, 
      Activity_Type_Name: 'HUNTING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 58, 
      Activity_Type_Name: 'FISHING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 59, 
      Activity_Type_Name: 'INLINE SKATING',
      Strava_Activity_Type_Name: 'InlineSkate',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 60, 
      Activity_Type_Name: 'MOUNTAINEERING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 61, 
      Activity_Type_Name: 'OFFSHORE GRINDING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 62, 
      Activity_Type_Name: 'ONSHORE GRINDING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 63, 
      Activity_Type_Name: 'PADDLING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 64, 
      Activity_Type_Name: 'RC',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 65, 
      Activity_Type_Name: 'ROCK CLIMBING',
      Strava_Activity_Type_Name: 'RockClimbing',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 66, 
      Activity_Type_Name: 'ROWING',
      Strava_Activity_Type_Name: 'Rowing',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 67, 
      Activity_Type_Name: 'SAILING',
      Strava_Activity_Type_Name: 'Sail',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 68, 
      Activity_Type_Name: 'SKY DIVING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 69, 
      Activity_Type_Name: 'STAND UP PADDLEBOARDING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 70, 
      Activity_Type_Name: 'STOPWATCH',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 71, 
      Activity_Type_Name: 'SURFING',
      Strava_Activity_Type_Name: 'Surfing',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 72, 
      Activity_Type_Name: 'TENNIS',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 73, 
      Activity_Type_Name: 'WAKEBOARDING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 74, 
      Activity_Type_Name: 'WHITEWATER KAYAKING',
      Strava_Activity_Type_Name: 'Kayaking',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 75, 
      Activity_Type_Name: 'WIND',
      Strava_Activity_Type_Name: 'Windsurf',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 76, 
      Activity_Type_Name: 'WINGSUIT FLYING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 77, 
      Activity_Type_Name: 'DIVING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 78, 
      Activity_Type_Name: 'APNEA',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 79, 
      Activity_Type_Name: 'APNEA HUNT',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 80, 
      Activity_Type_Name: 'CCR DIVE',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 81, 
      Activity_Type_Name: 'GAUGE DIVE',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 82, 
      Activity_Type_Name: 'MULTI-GAS DIVE',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 83, 
      Activity_Type_Name: 'SINGLE-GAS DIVE',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 84, 
      Activity_Type_Name: 'WINTER SPORTS',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 85, 
      Activity_Type_Name: 'BACKCOUNTRY SKIING',
      Strava_Activity_Type_Name: 'BackcountrySki',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 86, 
      Activity_Type_Name: 'CROSS COUNTRY CLASSIC SKIING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 87, 
      Activity_Type_Name: 'SNOWBOARDING',
      Strava_Activity_Type_Name: 'Snowboard',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 88, 
      Activity_Type_Name: 'CROSS COUNTRY SKATE SKIING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 89, 
      Activity_Type_Name: 'SKATING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 90, 
      Activity_Type_Name: 'SNOWSHOEING',
      Strava_Activity_Type_Name: 'Snowshoe',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 91, 
      Activity_Type_Name: 'SNOWMOBILING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 92, 
      Activity_Type_Name: 'AlpineSki',
      Strava_Activity_Type_Name: 'AlpineSki',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 93, 
      Activity_Type_Name: 'Canoeing',
      Strava_Activity_Type_Name: 'Canoeing',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 94, 
      Activity_Type_Name: 'Crossfit',
      Strava_Activity_Type_Name: 'Crossfit',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 95, 
      Activity_Type_Name: 'EBikeRide',
      Strava_Activity_Type_Name: 'EBikeRide',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 96, 
      Activity_Type_Name: 'Handcycle',
      Strava_Activity_Type_Name: 'Handcycle',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 97, 
      Activity_Type_Name: 'IceSkate',
      Strava_Activity_Type_Name: 'IceSkate',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 98, 
      Activity_Type_Name: 'NordicSki',
      Strava_Activity_Type_Name: 'NordicSki',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 99, 
      Activity_Type_Name: 'RollerSki',
      Strava_Activity_Type_Name: 'RollerSki',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 100, 
      Activity_Type_Name: 'Skateboard',
      Strava_Activity_Type_Name: 'Skateboard',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 101, 
      Activity_Type_Name: 'Soccer',
      Strava_Activity_Type_Name: 'Soccer',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 102, 
      Activity_Type_Name: 'StandUpPaddling',
      Strava_Activity_Type_Name: 'StandUpPaddling',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 103, 
      Activity_Type_Name: 'Velomobile',
      Strava_Activity_Type_Name: 'Velomobile',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 104, 
      Activity_Type_Name: 'Wheelchair',
      Strava_Activity_Type_Name: 'Wheelchair',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 105, 
      Activity_Type_Name: 'Workout',
      Strava_Activity_Type_Name: 'Workout',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 106, 
      Activity_Type_Name: 'UNPAVED CYCLING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 107, 
      Activity_Type_Name: 'INDOOR WALKING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 108, 
      Activity_Type_Name: 'DRONE',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 109, 
      Activity_Type_Name: 'RAFTING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 110, 
      Activity_Type_Name: 'KITE SURFING',
      Strava_Activity_Type_Name: 'Kitesurf',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 111, 
      Activity_Type_Name: 'RESORT SKIING',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
    {
      Activity_Type_ID: 112, 
      Activity_Type_Name: 'JOINING BONUS',
      Strava_Activity_Type_Name: '',
      AppleHealth_Activity_Type_Name: '',
    },
  ]).onConflict('Activity_Type_ID').ignore();
};
